import { Inter } from 'next/font/google'
import './globals.css'

// import 'components/Navbar.css'
import Navbar from 'components/Navbar.js'
import 'bootstrap/dist/css/bootstrap.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
    <body>
      <Navbar />

      {children}
    </body>
  </html>
  )
}
